PKX-1437
PakistanX/ecommerce pull request #16
Opened 2024-04-25 14:07 UTC by hamzatanveer012

## Anyone merging to this repository is expected to [release and monitor their changes](https://openedx.atlassian.net/wiki/spaces/RS/pages/1835106870/How+to+contribute+to+our+repositories); if you are not able to do this DO NOT MERGE, please coordinate with someone who can to ensure that the changes are released.

## Description

Describe what this pull request changes, and why these changes were made. How will these changes affect other people, installations of edx, etc.?
Please include links to any relevant ADRs, design artifacts, and decision documents. Make sure to document the rationale behind significant changes in the repo, per [OEP-19](https://open-edx-proposals.readthedocs.io/en/latest/oep-0019-bp-developer-documentation.html), and can be
linked here.

Useful information to include:
- Which edX user roles will this change impact? Common user roles are "Learner", "Course Author", "Developer", and "Operator".
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these changes.

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

Please provide detailed step-by-step instructions for testing this change; how did YOU test this change?

## Other information

Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, OpenEdx vs. edx.org differences, development vs. production environment differences, security, or accessibility.

2024-04-26 06:16 UTC, m-usman01 commented on ecommerce/extensions/payment/processors/xstack.py
> +        logger.info('Generated str: {}'.format(query_str))
Too many logs, add a TODO comment here to remove these once everything has been finalised

2024-04-26 06:16 UTC, m-usman01 commented on ecommerce/extensions/payment/views/xstack.py
> +            ])),
Why are we hard coding this?

2024-04-26 10:30 UTC, ahmadshafique commented on ecommerce/settings/base.py
Unnecessary changes. Pls remove them

2024-04-29 12:15 UTC, m-usman01 approved these changes

2024-04-30 14:03 UTC, ahmadshafique commented on ecommerce/settings/base.py
> -MEDIA_STORAGE_BACKEND = {
Please revert these changes as well

2024-05-06 09:32 UTC, ahmadshafique commented on ecommerce/settings/base.py
> -MEDIA_STORAGE_BACKEND = {
@hamzatanveer012 ^

2024-05-06 17:30 UTC, ahmadshafique requested changes

2024-05-06 17:30 UTC, ahmadshafique commented on ecommerce/extensions/payment/views/xstack.py
> +                ('country', ''),
@hamzatanveer012 pass country and province data as passed from the updated form by Tanveer.

2024-05-07 11:27 UTC, ahmadshafique approved these changes

2024-05-07 11:27 UTC, merged